[package]
name = "jellrust-template"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
liquid.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true

